In [1]:
import soccerdata as sd
understat = sd.Understat(leagues="ENG-Premier League", seasons="2023/2024")
team_match_stats = understat.read_team_match_stats()
team_match_stats.head()

[03/26/24 19:27:32] INFO     No custom team name replacements found. You can configure these in       ]8;id=893079;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=794000;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_config.py#87\87]8;;\
                             C:\Users\jbuck\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=904059;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=208059;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_config.py#177\177]8;;\
                             C:\Users\jbuck\soccerdata\config\league_dict.json.

                    INFO     Saving cached data to C:\Users\jbuck\soccerdata\data\Understat           ]8;id=49176;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=179043;file://C:\Users\jbuck\anaconda3\Lib\site-packages\soccerdata\_common.py#91\91]8;;\

                                                               league_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City           1
                          2023-08-12 Arsenal-Nottingham Forest         1
                          2023-08-12 Bournemouth-West Ham              1
                          2023-08-12 Brighton-Luton                    1
                          2023-08-12 Everton-Fulham                    1

                                                                season_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City         2023
                          2023-08-12 Arsenal-Nottingham Forest       2023
                          2023-08-12 Bournemouth-West Ham            2023
                          2023-08-12 Brighton-Luton                  2023
                          2023-08-12 Everton-Fulham                  2023

                                                                game_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City      22275
                          2023-08-12 Arsenal-Nottingham Forest    22276
                          2023-08-12 Bournemouth-West Ham         22277
                          2023-08-12 Brighton-Luton               22278
                          2023-08-12 Everton-Fulham               22279

                                                                              date  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City   2023-08-11 19:00:00
                          2023-08-12 Arsenal-Nottingham Forest 2023-08-12 11:30:00
                          2023-08-12 Bournemouth-West Ham      2023-08-12 14:00:00
                          2023-08-12 Brighton-Luton            2023-08-12 14:00:00
                          2023-08-12 Everton-Fulham            2023-08-12 14:00:00

                                                                home_team_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              92
                          2023-08-12 Arsenal-Nottingham Forest            83
                          2023-08-12 Bournemouth-West Ham                 73
                          2023-08-12 Brighton-Luton                      220
                          2023-08-12 Everton-Fulham                       72

                                                                away_team_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              88
                          2023-08-12 Arsenal-Nottingham Forest           249
                          2023-08-12 Bournemouth-West Ham                 81
                          2023-08-12 Brighton-Luton                      256
                          2023-08-12 Everton-Fulham                      228

                                                                  home_team  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City        Burnley
                          2023-08-12 Arsenal-Nottingham Forest      Arsenal
                          2023-08-12 Bournemouth-West Ham       Bournemouth
                          2023-08-12 Brighton-Luton                Brighton
                          2023-08-12 Everton-Fulham                 Everton

                                                                        away_team  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City      Manchester City
                          2023-08-12 Arsenal-Nottingham Forest  Nottingham Forest
                          2023-08-12 Bournemouth-West Ham                West Ham
                          2023-08-12 Brighton-Luton                         Luton
                          2023-08-12 Everton-Fulham                        Fulham

                                                               away_team_code  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              MCI
                          2023-08-12 Arsenal-Nottingham Forest            NOT
                          2023-08-12 Bournemouth-West Ham                 WHU
                          2023-08-12 Brighton-Luton                       LUT
                          2023-08-12 Everton-Fulham                       FLH

                                                               home_team_code  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              BUR
                          2023-08-12 Arsenal-Nottingham Forest            ARS
                          2023-08-12 Bournemouth-West Ham                 BOU
                          2023-08-12 Brighton-Luton                       BRI
                          2023-08-12 Everton-Fulham                       EVE

                                                                ...  \
league             season game                                  ...
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    ...
                          2023-08-12 Arsenal-Nottingham Forest  ...
                          2023-08-12 Bournemouth-West Ham       ...
                          2023-08-12 Brighton-Luton             ...
                          2023-08-12 Everton-Fulham             ...

                                                                away_ppda  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City         15.8
                          2023-08-12 Arsenal-Nottingham Forest       44.1
                          2023-08-12 Bournemouth-West Ham        9.733333
                          2023-08-12 Brighton-Luton               23.0625
                          2023-08-12 Everton-Fulham                  17.4

                                                                away_deep_completions  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City                        9
                          2023-08-12 Arsenal-Nottingham Forest                      4
                          2023-08-12 Bournemouth-West Ham                           8
                          2023-08-12 Brighton-Luton                                 5
                          2023-08-12 Everton-Fulham                                 6

                                                                home_points  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              0
                          2023-08-12 Arsenal-Nottingham Forest            3
                          2023-08-12 Bournemouth-West Ham                 1
                          2023-08-12 Brighton-Luton                       3
                          2023-08-12 Everton-Fulham                       0

                                                                home_expected_points  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City                  0.1385
                          2023-08-12 Arsenal-Nottingham Forest                1.1754
                          2023-08-12 Bournemouth-West Ham                     1.3846
                          2023-08-12 Brighton-Luton                           2.7246
                          2023-08-12 Everton-Fulham                           2.1102

                                                                home_goals  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City             0
                          2023-08-12 Arsenal-Nottingham Forest           2
                          2023-08-12 Bournemouth-West Ham                1
                          2023-08-12 Brighton-Luton                      4
                          2023-08-12 Everton-Fulham                      0

                                                                 home_xg  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    0.311032
                          2023-08-12 Arsenal-Nottingham Forest   0.84262
                          2023-08-12 Bournemouth-West Ham        1.51025
                          2023-08-12 Brighton-Luton              4.36748
                          2023-08-12 Everton-Fulham              2.59001

                                                                home_np_xg  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City      0.311032
                          2023-08-12 Arsenal-Nottingham Forest     0.84262
                          2023-08-12 Bournemouth-West Ham          1.51025
                          2023-08-12 Brighton-Luton                3.60631
                          2023-08-12 Everton-Fulham                2.59001

                                                                home_np_xg_difference  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City                -2.089708
                          2023-08-12 Arsenal-Nottingham Forest              -0.123685
                          2023-08-12 Bournemouth-West Ham                     0.02685
                          2023-08-12 Brighton-Luton                           2.48154
                          2023-08-12 Everton-Fulham                           1.00857

                                                                home_ppda  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    33.071429
                          2023-08-12 Arsenal-Nottingham Forest        4.0
                          2023-08-12 Bournemouth-West Ham        5.111111
                          2023-08-12 Brighton-Luton                 6.875
                          2023-08-12 Everton-Fulham             14.826087

                                                                home_deep_completions
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City                        4
                          2023-08-12 Arsenal-Nottingham Forest                      9
                          2023-08-12 Bournemouth-West Ham                           9
                          2023-08-12 Brighton-Luton                                17
                          2023-08-12 Everton-Fulham                                 7

[5 rows x 26 columns]

In [2]:
import pandas as pd

# Assuming 'team_match_stats' is your DataFrame loaded from the code you've provided

# Calculating total xG for teams when they are at home
home_xg = team_match_stats.groupby('home_team')['home_xg'].sum().rename('total_home_xg')

# Calculating total xG for teams when they are away
away_xg = team_match_stats.groupby('away_team')['away_xg'].sum().rename('total_away_xg')

# Calculating total xGA (expected goals against) for teams when they are at home
home_xga = team_match_stats.groupby('home_team')['away_xg'].sum().rename('total_home_xga')

# Calculating total xGA for teams when they are away
away_xga = team_match_stats.groupby('away_team')['home_xg'].sum().rename('total_away_xga')

# Merging the above series into a single DataFrame
teams_xg_xga = pd.concat([home_xg, away_xg, home_xga, away_xga], axis=1)

# Filling NaN values with 0, in case some teams didn't play home or away games yet
teams_xg_xga = teams_xg_xga.fillna(0)

# Calculating overall total xG and xGA
teams_xg_xga['total_xg'] = teams_xg_xga['total_home_xg'] + teams_xg_xga['total_away_xg']
teams_xg_xga['total_xga'] = teams_xg_xga['total_home_xga'] + teams_xg_xga['total_away_xga']

teams_xg_xga

,total_home_xg,total_away_xg,total_home_xga,total_away_xga,total_xg,total_xga
Arsenal,33.802748,27.387759,11.327594,11.526997,61.190507,22.854591
Aston Villa,31.522419,24.719727,20.089948,25.752484,56.242146,45.842432
Bournemouth,23.215629,24.356539,22.446284,27.218903,47.572168,49.665187
Brentford,27.776994,21.239744,23.574625,24.584212,49.016738,48.158837
Brighton,27.682338,21.470854,17.937619,23.896931,49.153192,41.83455
Burnley,18.99238,11.382325,24.929651,29.884165,30.374705,54.813816
Chelsea,29.59185,24.287505,16.793008,27.168489,53.879355,43.961497
Crystal Palace,21.074452,15.141141,16.88216,28.318358,36.215593,45.200518
Everton,29.870607,19.076757,18.438484,25.413238,48.947364,43.851722
Fulham,26.564272,14.756725,23.025973,29.40323,41.320997,52.429203
Liverpool,41.800291,23.765951,13.550334,21.601115,65.566242,35.151449
Luton,24.908574,17.094423,28.5986,42.8548,42.002997,71.4534
Manchester City,28.684689,33.327591,11.339534,16.615904,62.01228,27.955438
Manchester United,25.128062,20.338901,23.405779,26.743962,45.466963,50.149741
Newcastle United,36.83946,20.729532,18.188147,30.340725,57.568992,48.528872
Nottingham Forest,18.127917,18.209143,15.681094,28.161582,36.33706,43.842676
Sheffield United,16.891021,10.668794,34.124813,30.51933,27.559815,64.644143
Tottenham,31.176918,22.868776,23.62546,26.065927,54.045694,49.691387
West Ham,20.87713,21.609768,23.498158,30.62324,42.486898,54.121398
Wolverhampton Wanderers,20.813431,19.502669,24.47736,28.64759,40.3161,53.12495

In [3]:
import pandas as pd

# Identify all unique teams
teams = pd.concat([team_match_stats['home_team'], team_match_stats['away_team']]).unique()

# Prepare a list to collect each team's average xG and xGA
team_averages = []

# Iterate through each team
for team in teams:
    # Filter games involving the current team
    team_games = team_match_stats[(team_match_stats['home_team'] == team) | (team_match_stats['away_team'] == team)]
    
    # Sort games by date in descending order
    team_games_sorted = team_games.sort_values(by='date', ascending=False)
    
    # Select the last 5 games
    team_last_5_games = team_games_sorted.head(5)
    
    # Calculate average xG and xGA for the team
    team_xg = team_last_5_games.apply(lambda row: row['home_xg'] if row['home_team'] == team else row['away_xg'], axis=1).mean()
    team_xga = team_last_5_games.apply(lambda row: row['away_xg'] if row['home_team'] == team else row['home_xg'], axis=1).mean()
    
    # Append the averages to the list
    team_averages.append({
        'Team': team,
        'Average xG Last 5': team_xg,
        'Average xGA Last 5': team_xga
    })

# Convert the list of averages into a DataFrame
teams_xg_xga_df = pd.DataFrame(team_averages)

# Display the DataFrame
teams_xg_xga_df

                       Team  Average xG Last 5  Average xGA Last 5
0                   Burnley           1.118969            1.836680
1                   Arsenal           2.572934            0.335639
2               Bournemouth           2.242726            2.099386
3                  Brighton           1.637728            1.009045
4                   Everton           1.573351            1.811855
5          Newcastle United           1.403277            1.586667
6          Sheffield United           1.068456            2.546666
7                 Brentford           1.259660            2.210028
8                   Chelsea           1.878726            1.805648
9         Manchester United           2.210273            1.964144
10        Nottingham Forest           1.707258            1.343903
11                   Fulham           1.869278            1.625368
12                Liverpool           2.703478            1.221456
13          Manchester City           2.225154            1.133480
14                Tottenham           2.153782            1.450331
15  Wolverhampton Wanderers           1.170712            2.075520
16              Aston Villa           1.858277            1.937774
17                 West Ham           1.594131            1.783917
18           Crystal Palace           1.479848            1.507838
19                    Luton           1.624583            2.767324

In [4]:
# Count the number of home matches played by each team
home_matches_played = team_match_stats.groupby('home_team')['home_ppda'].count().rename('home_matches_played')

# Count the number of away matches played by each team
away_matches_played = team_match_stats.groupby('away_team')['away_ppda'].count().rename('away_matches_played')

# Merging these counts into the teams_xg_xga DataFrame
teams_xg_xga = teams_xg_xga.merge(home_matches_played, how='left', left_index=True, right_index=True)
teams_xg_xga = teams_xg_xga.merge(away_matches_played, how='left', left_index=True, right_index=True)

# Filling NaN values with 0 in case some teams didn't play home or away games
teams_xg_xga['home_matches_played'] = teams_xg_xga['home_matches_played'].fillna(0)
teams_xg_xga['away_matches_played'] = teams_xg_xga['away_matches_played'].fillna(0)

# Calculating the total matches played by adding home and away matches
teams_xg_xga['matches_played'] = teams_xg_xga['home_matches_played'] + teams_xg_xga['away_matches_played']

teams_xg_xga

,total_home_xg,total_away_xg,total_home_xga,total_away_xga,total_xg,total_xga,home_matches_played,away_matches_played,matches_played
Arsenal,33.802748,27.387759,11.327594,11.526997,61.190507,22.854591,14,14,28
Aston Villa,31.522419,24.719727,20.089948,25.752484,56.242146,45.842432,14,15,29
Bournemouth,23.215629,24.356539,22.446284,27.218903,47.572168,49.665187,14,14,28
Brentford,27.776994,21.239744,23.574625,24.584212,49.016738,48.158837,14,15,29
Brighton,27.682338,21.470854,17.937619,23.896931,49.153192,41.83455,14,14,28
Burnley,18.99238,11.382325,24.929651,29.884165,30.374705,54.813816,15,14,29
Chelsea,29.59185,24.287505,16.793008,27.168489,53.879355,43.961497,13,14,27
Crystal Palace,21.074452,15.141141,16.88216,28.318358,36.215593,45.200518,14,14,28
Everton,29.870607,19.076757,18.438484,25.413238,48.947364,43.851722,14,14,28
Fulham,26.564272,14.756725,23.025973,29.40323,41.320997,52.429203,15,14,29
Liverpool,41.800291,23.765951,13.550334,21.601115,65.566242,35.151449,14,14,28
Luton,24.908574,17.094423,28.5986,42.8548,42.002997,71.4534,15,14,29
Manchester City,28.684689,33.327591,11.339534,16.615904,62.01228,27.955438,14,14,28
Manchester United,25.128062,20.338901,23.405779,26.743962,45.466963,50.149741,14,14,28
Newcastle United,36.83946,20.729532,18.188147,30.340725,57.568992,48.528872,14,14,28
Nottingham Forest,18.127917,18.209143,15.681094,28.161582,36.33706,43.842676,14,15,29
Sheffield United,16.891021,10.668794,34.124813,30.51933,27.559815,64.644143,14,14,28
Tottenham,31.176918,22.868776,23.62546,26.065927,54.045694,49.691387,14,14,28
West Ham,20.87713,21.609768,23.498158,30.62324,42.486898,54.121398,15,14,29
Wolverhampton Wanderers,20.813431,19.502669,24.47736,28.64759,40.3161,53.12495,14,14,28

In [5]:
# Calculating xG difference for home games
teams_xg_xga['home_xg_diff'] = teams_xg_xga['total_home_xg'] - teams_xg_xga['total_home_xga']

# Calculating xG difference for away games
teams_xg_xga['away_xg_diff'] = teams_xg_xga['total_away_xg'] - teams_xg_xga['total_away_xga']

# Display the updated DataFrame
teams_xg_xga

,total_home_xg,total_away_xg,total_home_xga,total_away_xga,total_xg,total_xga,home_matches_played,away_matches_played,matches_played,home_xg_diff,away_xg_diff
Arsenal,33.802748,27.387759,11.327594,11.526997,61.190507,22.854591,14,14,28,22.475154,15.860762
Aston Villa,31.522419,24.719727,20.089948,25.752484,56.242146,45.842432,14,15,29,11.432471,-1.032757
Bournemouth,23.215629,24.356539,22.446284,27.218903,47.572168,49.665187,14,14,28,0.769345,-2.862364
Brentford,27.776994,21.239744,23.574625,24.584212,49.016738,48.158837,14,15,29,4.202369,-3.344468
Brighton,27.682338,21.470854,17.937619,23.896931,49.153192,41.83455,14,14,28,9.744719,-2.426077
Burnley,18.99238,11.382325,24.929651,29.884165,30.374705,54.813816,15,14,29,-5.937271,-18.50184
Chelsea,29.59185,24.287505,16.793008,27.168489,53.879355,43.961497,13,14,27,12.798842,-2.880984
Crystal Palace,21.074452,15.141141,16.88216,28.318358,36.215593,45.200518,14,14,28,4.192292,-13.177217
Everton,29.870607,19.076757,18.438484,25.413238,48.947364,43.851722,14,14,28,11.432123,-6.336481
Fulham,26.564272,14.756725,23.025973,29.40323,41.320997,52.429203,15,14,29,3.538299,-14.646505
Liverpool,41.800291,23.765951,13.550334,21.601115,65.566242,35.151449,14,14,28,28.249958,2.164836
Luton,24.908574,17.094423,28.5986,42.8548,42.002997,71.4534,15,14,29,-3.690026,-25.760377
Manchester City,28.684689,33.327591,11.339534,16.615904,62.01228,27.955438,14,14,28,17.345155,16.711687
Manchester United,25.128062,20.338901,23.405779,26.743962,45.466963,50.149741,14,14,28,1.722283,-6.405061
Newcastle United,36.83946,20.729532,18.188147,30.340725,57.568992,48.528872,14,14,28,18.651313,-9.611193
Nottingham Forest,18.127917,18.209143,15.681094,28.161582,36.33706,43.842676,14,15,29,2.446823,-9.952439
Sheffield United,16.891021,10.668794,34.124813,30.51933,27.559815,64.644143,14,14,28,-17.233792,-19.850536
Tottenham,31.176918,22.868776,23.62546,26.065927,54.045694,49.691387,14,14,28,7.551458,-3.197151
West Ham,20.87713,21.609768,23.498158,30.62324,42.486898,54.121398,15,14,29,-2.621028,-9.013472
Wolverhampton Wanderers,20.813431,19.502669,24.47736,28.64759,40.3161,53.12495,14,14,28,-3.663929,-9.144921

In [6]:
# Assuming 'teams_xg_xga' is your DataFrame

# Calculate the averages for each specified column
averages = teams_xg_xga.mean()

# Creating a new DataFrame with the averages to append it properly with a label
averages_df = pd.DataFrame([averages], index=['Average'])

# Append the averages row to your original DataFrame
teams_xg_xga_with_averages = pd.concat([teams_xg_xga, averages_df])

teams_xg_xga_with_averages

,total_home_xg,total_away_xg,total_home_xga,total_away_xga,total_xg,total_xga,home_matches_played,away_matches_played,matches_played,home_xg_diff,away_xg_diff
Arsenal,33.802748,27.387759,11.327594,11.526997,61.190507,22.854591,14.0,14.0,28.0,22.475154,15.860762
Aston Villa,31.522419,24.719727,20.089948,25.752484,56.242146,45.842432,14.0,15.0,29.0,11.432471,-1.032757
Bournemouth,23.215629,24.356539,22.446284,27.218903,47.572168,49.665187,14.0,14.0,28.0,0.769345,-2.862364
Brentford,27.776994,21.239744,23.574625,24.584212,49.016738,48.158837,14.0,15.0,29.0,4.202369,-3.344468
Brighton,27.682338,21.470854,17.937619,23.896931,49.153192,41.83455,14.0,14.0,28.0,9.744719,-2.426077
Burnley,18.99238,11.382325,24.929651,29.884165,30.374705,54.813816,15.0,14.0,29.0,-5.937271,-18.50184
Chelsea,29.59185,24.287505,16.793008,27.168489,53.879355,43.961497,13.0,14.0,27.0,12.798842,-2.880984
Crystal Palace,21.074452,15.141141,16.88216,28.318358,36.215593,45.200518,14.0,14.0,28.0,4.192292,-13.177217
Everton,29.870607,19.076757,18.438484,25.413238,48.947364,43.851722,14.0,14.0,28.0,11.432123,-6.336481
Fulham,26.564272,14.756725,23.025973,29.40323,41.320997,52.429203,15.0,14.0,29.0,3.538299,-14.646505
Liverpool,41.800291,23.765951,13.550334,21.601115,65.566242,35.151449,14.0,14.0,28.0,28.249958,2.164836
Luton,24.908574,17.094423,28.5986,42.8548,42.002997,71.4534,15.0,14.0,29.0,-3.690026,-25.760377
Manchester City,28.684689,33.327591,11.339534,16.615904,62.01228,27.955438,14.0,14.0,28.0,17.345155,16.711687
Manchester United,25.128062,20.338901,23.405779,26.743962,45.466963,50.149741,14.0,14.0,28.0,1.722283,-6.405061
Newcastle United,36.83946,20.729532,18.188147,30.340725,57.568992,48.528872,14.0,14.0,28.0,18.651313,-9.611193
Nottingham Forest,18.127917,18.209143,15.681094,28.161582,36.33706,43.842676,14.0,15.0,29.0,2.446823,-9.952439
Sheffield United,16.891021,10.668794,34.124813,30.51933,27.559815,64.644143,14.0,14.0,28.0,-17.233792,-19.850536
Tottenham,31.176918,22.868776,23.62546,26.065927,54.045694,49.691387,14.0,14.0,28.0,7.551458,-3.197151
West Ham,20.87713,21.609768,23.498158,30.62324,42.486898,54.121398,15.0,14.0,29.0,-2.621028,-9.013472
Wolverhampton Wanderers,20.813431,19.502669,24.47736,28.64759,40.3161,53.12495,14.0,14.0,28.0,-3.663929,-9.144921
Average,26.767059,20.596731,20.596731,26.767059,47.36379,47.36379,14.15,14.15,28.3,6.170328,-6.170328

In [7]:
import numpy as np

# Create a new DataFrame for per match averages
teams_per_match_averages = pd.DataFrame(index=teams_xg_xga.index)

# Calculate per match averages for home and away xG and xGA
teams_per_match_averages['per_match_home_xg'] = teams_xg_xga['total_home_xg'] / teams_xg_xga['home_matches_played']
teams_per_match_averages['per_match_away_xg'] = teams_xg_xga['total_away_xg'] / teams_xg_xga['away_matches_played']
teams_per_match_averages['per_match_home_xga'] = teams_xg_xga['total_home_xga'] / teams_xg_xga['home_matches_played']
teams_per_match_averages['per_match_away_xga'] = teams_xg_xga['total_away_xga'] / teams_xg_xga['away_matches_played']

# Calculate overall total xG and xGA per match
teams_per_match_averages['total_xg_per_match'] = teams_xg_xga['total_xg'] / teams_xg_xga['matches_played']
teams_per_match_averages['total_xga_per_match'] = teams_xg_xga['total_xga'] / teams_xg_xga['matches_played']

# Replace any potential infinite values with NaN (in case of division by zero) and then fill with 0
teams_per_match_averages.replace([np.inf, -np.inf], np.nan, inplace=True)
teams_per_match_averages.fillna(0, inplace=True)

# Calculate the average for each column
average_stats = teams_per_match_averages.mean()

# Append the 'Average' row with these averages to the DataFrame
teams_per_match_averages.loc['Average'] = average_stats

teams_per_match_averages

,per_match_home_xg,per_match_away_xg,per_match_home_xga,per_match_away_xga,total_xg_per_match,total_xga_per_match
Arsenal,2.414482,1.956268,0.809114,0.823357,2.185375,0.816235
Aston Villa,2.251601,1.647982,1.434996,1.716832,1.939384,1.580774
Bournemouth,1.658259,1.739753,1.603306,1.944207,1.699006,1.773757
Brentford,1.984071,1.415983,1.683902,1.638947,1.690232,1.66065
Brighton,1.97731,1.533632,1.281258,1.706924,1.755471,1.494091
Burnley,1.266159,0.813023,1.661977,2.134583,1.047404,1.890132
Chelsea,2.276296,1.734822,1.29177,1.940606,1.995532,1.628204
Crystal Palace,1.505318,1.08151,1.205869,2.02274,1.293414,1.614304
Everton,2.133615,1.362626,1.317035,1.815231,1.74812,1.566133
Fulham,1.770951,1.054052,1.535065,2.100231,1.424862,1.807904
Liverpool,2.985735,1.697568,0.967881,1.542937,2.341652,1.255409
Luton,1.660572,1.22103,1.906573,3.061057,1.448379,2.46391
Manchester City,2.048906,2.380542,0.809967,1.18685,2.214724,0.998409
Manchester United,1.794862,1.452779,1.671841,1.910283,1.62382,1.791062
Newcastle United,2.63139,1.480681,1.299153,2.167195,2.056035,1.733174
Nottingham Forest,1.294851,1.213943,1.120078,1.877439,1.253002,1.511816
Sheffield United,1.206502,0.762057,2.437487,2.179952,0.984279,2.308719
Tottenham,2.226923,1.633484,1.687533,1.861852,1.930203,1.774692
West Ham,1.391809,1.543555,1.566544,2.187374,1.465065,1.866255
Wolverhampton Wanderers,1.486674,1.393048,1.748383,2.046256,1.439861,1.89732
Average,1.898314,1.455917,1.451987,1.893243,1.676791,1.671647

In [8]:
# Load the full schedule
schedule_df = understat.read_schedule()

# Convert the 'date' column to datetime format, then format it to keep only the date part
schedule_df['date'] = pd.to_datetime(schedule_df['date']).dt.date

# Display the first few rows to verify the change
print(schedule_df.head())

                                                               league_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City           1
                          2023-08-12 Arsenal-Nottingham Forest         1
                          2023-08-12 Bournemouth-West Ham              1
                          2023-08-12 Brighton-Luton                    1
                          2023-08-12 Everton-Fulham                    1

                                                                season_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City         2023
                          2023-08-12 Arsenal-Nottingham Forest       2023
                          2023-08-12 Bournemouth-West Ham            2023
                          2023-08-12 Brighton-Luton                  2023
                          2023-08-12 Everton-Fulham                  2023

                                                                game_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City      22275
                          2023-08-12 Arsenal-Nottingham Forest    22276
                          2023-08-12 Bournemouth-West Ham         22277
                          2023-08-12 Brighton-Luton               22278
                          2023-08-12 Everton-Fulham               22279

                                                                      date  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    2023-08-11
                          2023-08-12 Arsenal-Nottingham Forest  2023-08-12
                          2023-08-12 Bournemouth-West Ham       2023-08-12
                          2023-08-12 Brighton-Luton             2023-08-12
                          2023-08-12 Everton-Fulham             2023-08-12

                                                                home_team_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              92
                          2023-08-12 Arsenal-Nottingham Forest            83
                          2023-08-12 Bournemouth-West Ham                 73
                          2023-08-12 Brighton-Luton                      220
                          2023-08-12 Everton-Fulham                       72

                                                                away_team_id  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              88
                          2023-08-12 Arsenal-Nottingham Forest           249
                          2023-08-12 Bournemouth-West Ham                 81
                          2023-08-12 Brighton-Luton                      256
                          2023-08-12 Everton-Fulham                      228

                                                                  home_team  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City        Burnley
                          2023-08-12 Arsenal-Nottingham Forest      Arsenal
                          2023-08-12 Bournemouth-West Ham       Bournemouth
                          2023-08-12 Brighton-Luton                Brighton
                          2023-08-12 Everton-Fulham                 Everton

                                                                        away_team  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City      Manchester City
                          2023-08-12 Arsenal-Nottingham Forest  Nottingham Forest
                          2023-08-12 Bournemouth-West Ham                West Ham
                          2023-08-12 Brighton-Luton                         Luton
                          2023-08-12 Everton-Fulham                        Fulham

                                                               away_team_code  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              MCI
                          2023-08-12 Arsenal-Nottingham Forest            NOT
                          2023-08-12 Bournemouth-West Ham                 WHU
                          2023-08-12 Brighton-Luton                       LUT
                          2023-08-12 Everton-Fulham                       FLH

                                                               home_team_code  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City              BUR
                          2023-08-12 Arsenal-Nottingham Forest            ARS
                          2023-08-12 Bournemouth-West Ham                 BOU
                          2023-08-12 Brighton-Luton                       BRI
                          2023-08-12 Everton-Fulham                       EVE

                                                                home_goals  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City             0
                          2023-08-12 Arsenal-Nottingham Forest           2
                          2023-08-12 Bournemouth-West Ham                1
                          2023-08-12 Brighton-Luton                      4
                          2023-08-12 Everton-Fulham                      0

                                                                away_goals  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City             3
                          2023-08-12 Arsenal-Nottingham Forest           1
                          2023-08-12 Bournemouth-West Ham                1
                          2023-08-12 Brighton-Luton                      1
                          2023-08-12 Everton-Fulham                      1

                                                                 home_xg  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    0.311032
                          2023-08-12 Arsenal-Nottingham Forest   0.84262
                          2023-08-12 Bournemouth-West Ham        1.51025
                          2023-08-12 Brighton-Luton              4.36748
                          2023-08-12 Everton-Fulham              2.59001

                                                                 away_xg  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City     2.40074
                          2023-08-12 Arsenal-Nottingham Forest  0.966305
                          2023-08-12 Bournemouth-West Ham         1.4834
                          2023-08-12 Brighton-Luton              1.88594
                          2023-08-12 Everton-Fulham              1.58144

                                                                is_result  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City         True
                          2023-08-12 Arsenal-Nottingham Forest       True
                          2023-08-12 Bournemouth-West Ham            True
                          2023-08-12 Brighton-Luton                  True
                          2023-08-12 Everton-Fulham                  True

                                                                has_data  \
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City        True
                          2023-08-12 Arsenal-Nottingham Forest      True
                          2023-08-12 Bournemouth-West Ham           True
                          2023-08-12 Brighton-Luton                 True
                          2023-08-12 Everton-Fulham                 True

                                                                                              url
league             season game
ENG-Premier League 2324   2023-08-11 Burnley-Manchester City    https://understat.com/match/22275
                          2023-08-12 Arsenal-Nottingham Forest  https://understat.com/match/22276
                          2023-08-12 Bournemouth-West Ham       https://understat.com/match/22277
                          2023-08-12 Brighton-Luton             https://understat.com/match/22278
                          2023-08-12 Everton-Fulham             https://understat.com/match/22279

In [9]:
import pandas as pd

# Assuming 'schedule_df' is your DataFrame and it's already loaded

# Make sure the 'date' column is in datetime format
schedule_df['date'] = pd.to_datetime(schedule_df['date'])

# Define the start and end dates for filtering
start_date = pd.to_datetime('2024-03-29')
end_date = pd.to_datetime('2024-04-01')

# Filter the DataFrame for games within the date range, and use .copy() to avoid SettingWithCopyWarning
filtered_games = schedule_df[(schedule_df['date'] >= start_date) & (schedule_df['date'] <= end_date)].copy()

# Create a new column 'game_matchup' by concatenating 'home_team', 'vs.', and 'away_team'
filtered_games['game_matchup'] = filtered_games['home_team'] + ' vs. ' + filtered_games['away_team']

# Now, create a separate DataFrame that contains only the 'game_matchup' column
games_list_df = filtered_games[['game_matchup']].reset_index(drop=True)

# Display the new DataFrame to verify
print(games_list_df)

                              game_matchup
0  Aston Villa vs. Wolverhampton Wanderers
1                  Bournemouth vs. Everton
2          Brentford vs. Manchester United
3                      Chelsea vs. Burnley
4            Newcastle United vs. West Ham
5     Nottingham Forest vs. Crystal Palace
6              Sheffield United vs. Fulham
7                      Tottenham vs. Luton
8                   Liverpool vs. Brighton
9              Manchester City vs. Arsenal

In [10]:
import pandas as pd

# Assuming 'teams_per_match_averages' and 'games_list_df' are already defined

# Initialize an empty list for storing game metrics along with the matchup information
games_metrics_list = []

# Retrieve the 'Average' row for league-wide average stats
avg_stats = teams_per_match_averages.loc['Average']

# Looping through each game to calculate metrics using 'teams_per_match_averages'
for index, row in games_list_df.iterrows():
    # Extract home and away team names
    home_team, away_team = row['game_matchup'].split(' vs. ')
    
    # Retrieve team stats from 'teams_per_match_averages'
    home_team_stats = teams_per_match_averages.loc[home_team]
    away_team_stats = teams_per_match_averages.loc[away_team]
    
    # Calculate the metrics using the per match averages
    home_attack = home_team_stats['per_match_home_xg'] / avg_stats['per_match_home_xg']
    away_defence = away_team_stats['per_match_away_xga'] / avg_stats['per_match_away_xga']
    away_attack = away_team_stats['per_match_away_xg'] / avg_stats['per_match_away_xg']
    home_defence = home_team_stats['per_match_home_xga'] / avg_stats['per_match_home_xga']
    
    # Append the calculated metrics for this game to the list along with the game_matchup
    games_metrics_list.append({
        'Game Matchup': row['game_matchup'],
        'Home Attack': home_attack, 
        'Away Defence': away_defence,
        'Away Attack': away_attack, 
        'Home Defence': home_defence
    })

# Once all games are processed, create the DataFrame from the list
games_metrics_df = pd.DataFrame(games_metrics_list)

# Display the DataFrame with calculated metrics for each game
games_metrics_df

,Game Matchup,Home Attack,Away Defence,Away Attack,Home Defence
0,Aston Villa vs. Wolverhampton Wanderers,1.186106,1.080821,0.956818,0.988299
1,Bournemouth vs. Everton,0.873543,0.958795,0.935923,1.104215
2,Brentford vs. Manchester United,1.045175,1.009001,0.997845,1.159723
3,Chelsea vs. Burnley,1.199115,1.127475,0.558427,0.889657
4,Newcastle United vs. West Ham,1.386172,1.155359,1.060194,0.894742
5,Nottingham Forest vs. Crystal Palace,0.682106,1.068400,0.742838,0.771411
6,Sheffield United vs. Fulham,0.635565,1.109330,0.723978,1.678725
7,Tottenham vs. Luton,1.173105,1.616833,0.838668,1.162223
8,Liverpool vs. Brighton,1.572835,0.901587,1.053379,0.666591
9,Manchester City vs. Arsenal,1.079329,0.434892,1.343668,0.557833

In [11]:
# Initialize an empty list for storing projected goals data
projected_goals_list = []

# Retrieve the league-wide average per match home and away xG
league_avg_per_match_home_xg = teams_per_match_averages.loc['Average', 'per_match_home_xg']
league_avg_per_match_away_xg = teams_per_match_averages.loc['Average', 'per_match_away_xg']

# Iterate over each row in the games_metrics_df to calculate projected goals
for index, row in games_metrics_df.iterrows():
    # Extract home and away team names from the game matchup
    home_team, away_team = row['Game Matchup'].split(' vs. ')

    # Calculate metrics using the teams' attack and defence strengths
    home_attack = row['Home Attack']
    away_defence = row['Away Defence']
    away_attack = row['Away Attack']
    home_defence = row['Home Defence']

    # Calculate projected home and away goals using the league-wide average per game xG
    projected_home_goals = home_attack * away_defence * league_avg_per_match_home_xg
    projected_away_goals = away_attack * home_defence * league_avg_per_match_away_xg

    # Calculate total projected goals
    total_projected_goals = projected_home_goals + projected_away_goals

    # Append the results to the list
    projected_goals_list.append({
        'Game Matchup': row['Game Matchup'],
        'Projected Home Goals': projected_home_goals,
        'Projected Away Goals': projected_away_goals,
        'Total Projected Goals': total_projected_goals
    })

# Convert the list to a DataFrame
projected_goals_df = pd.DataFrame(projected_goals_list)

# Display the DataFrame
projected_goals_df

,Game Matchup,Projected Home Goals,Projected Away Goals,Total Projected Goals
0,Aston Villa vs. Wolverhampton Wanderers,2.433578,1.376747,3.810325
1,Bournemouth vs. Everton,1.589930,1.504632,3.094562
2,Brentford vs. Manchester United,2.001929,1.684820,3.686749
3,Chelsea vs. Burnley,2.566466,0.723312,3.289778
4,Newcastle United vs. West Ham,3.040199,1.381083,4.421282
5,Nottingham Forest vs. Crystal Palace,1.383419,0.834289,2.217707
6,Sheffield United vs. Fulham,1.338408,1.769463,3.107872
7,Tottenham vs. Luton,3.600562,1.419110,5.019672
8,Liverpool vs. Brighton,2.691901,1.022305,3.714206
9,Manchester City vs. Arsenal,0.891054,1.091272,1.982326

In [12]:
import numpy as np

# Number of simulations to run for each game
n_simulations = 10000

# Initialize lists to store the win/draw probabilities
home_win_probs = []
away_win_probs = []
draw_probs = []

for index, row in projected_goals_df.iterrows():
    home_goals_proj = row['Projected Home Goals']
    away_goals_proj = row['Projected Away Goals']

    # Simulate match outcomes
    home_goals_sim = np.random.poisson(home_goals_proj, n_simulations)
    away_goals_sim = np.random.poisson(away_goals_proj, n_simulations)

    # Calculate outcomes
    home_wins = np.sum(home_goals_sim > away_goals_sim)
    away_wins = np.sum(away_goals_sim > home_goals_sim)
    draws = np.sum(home_goals_sim == away_goals_sim)

    # Calculate probabilities
    home_win_prob = home_wins / n_simulations
    away_win_prob = away_wins / n_simulations
    draw_prob = draws / n_simulations

    # Append probabilities to lists
    home_win_probs.append(home_win_prob)
    away_win_probs.append(away_win_prob)
    draw_probs.append(draw_prob)

# Add the calculated probabilities to the projected_goals_df DataFrame
projected_goals_df['Home Win Probability'] = home_win_probs
projected_goals_df['Away Win Probability'] = away_win_probs
projected_goals_df['Draw Probability'] = draw_probs

# Convert probabilities to percentage format and append '%' sign
projected_goals_df['Home Win Probability'] = (projected_goals_df['Home Win Probability'] * 100).apply(lambda x: f'{x:.2f}%')
projected_goals_df['Away Win Probability'] = (projected_goals_df['Away Win Probability'] * 100).apply(lambda x: f'{x:.2f}%')
projected_goals_df['Draw Probability'] = (projected_goals_df['Draw Probability'] * 100).apply(lambda x: f'{x:.2f}%')

# Display the updated DataFrame with formatted probabilities
projected_goals_df

,Game Matchup,Projected Home Goals,Projected Away Goals,Total Projected Goals,Home Win Probability,Away Win Probability,Draw Probability
0,Aston Villa vs. Wolverhampton Wanderers,2.433578,1.376747,3.810325,61.04%,20.52%,18.44%
1,Bournemouth vs. Everton,1.589930,1.504632,3.094562,39.74%,36.76%,23.50%
2,Brentford vs. Manchester United,2.001929,1.684820,3.686749,45.58%,32.87%,21.55%
3,Chelsea vs. Burnley,2.566466,0.723312,3.289778,77.19%,8.31%,14.50%
4,Newcastle United vs. West Ham,3.040199,1.381083,4.421282,69.85%,14.92%,15.23%
5,Nottingham Forest vs. Crystal Palace,1.383419,0.834289,2.217707,49.85%,23.06%,27.09%
6,Sheffield United vs. Fulham,1.338408,1.769463,3.107872,29.31%,48.81%,21.88%
7,Tottenham vs. Luton,3.600562,1.419110,5.019672,77.30%,10.76%,11.94%
8,Liverpool vs. Brighton,2.691901,1.022305,3.714206,72.17%,12.57%,15.26%
9,Manchester City vs. Arsenal,0.891054,1.091272,1.982326,29.31%,39.55%,31.14%

In [13]:
import requests


# An api key is emailed to you when you sign up to a plan
# Get a free API key at https://api.the-odds-api.com/
API_KEY = '6ea2753ab77393e63fe86bb67324fc40'

SPORT = 'soccer' # use the sport_key from the /sports endpoint below, or use 'upcoming' to see the next 8 games across all sports

REGIONS = 'us' # uk | us | eu | au. Multiple can be specified if comma delimited

MARKETS = 'h2h,spreads' # h2h | spreads | totals. Multiple can be specified if comma delimited

ODDS_FORMAT = 'decimal' # decimal | american

DATE_FORMAT = 'iso' # iso | unix

In [14]:
import requests

# Your API key for the odds API
api_key = '6ea2753ab77393e63fe86bb67324fc40'

# Define the endpoint URL
url = 'https://api.the-odds-api.com/v4/sports/soccer_epl/odds/'

# Parameters for the API request
params = {
    'apiKey': api_key,
    'regions': 'us',  # Adjust if targeting a different region
    'markets': 'h2h',  # Head-to-head odds; adjust if looking for different market types
    'bookmakers': 'bovada',
    'oddsFormat': 'decimal'
}

# Make the GET request
response = requests.get(url, params=params)

# Check if the request was successful
if response.status_code == 200:
    # Convert the response to JSON
    odds_data = response.json()
    # Process your data here
    print(odds_data)
else:
    print(f"Error fetching data: {response.status_code}")

[{'id': '4606047aeb27e6856b3ff293ec578e43', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T12:30:00Z', 'home_team': 'Newcastle United', 'away_team': 'West Ham United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Newcastle United', 'price': 1.83}, {'name': 'West Ham United', 'price': 3.8}, {'name': 'Draw', 'price': 4.1}]}]}]}, {'id': '6619d3ca44afc07cccaee264d4f62977', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T15:00:00Z', 'home_team': 'Bournemouth', 'away_team': 'Everton', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Bournemouth', 'price': 2.15}, {'name': 'Everton', 'price': 3.25}, {'name': 'Draw', 'price': 3.6}]}]}]}, {'id': '2597298743f78005ba7c2b7f9cefd2a4', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T15:00:00Z', 'home_team': 'Chelsea', 'away_team': 'Burnley', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Burnley', 'price': 8.5}, {'name': 'Chelsea', 'price': 1.31}, {'name': 'Draw', 'price': 6.0}]}]}]}, {'id': 'd1e3eb5871c7e3b1ac9dabd09d94344f', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T15:00:00Z', 'home_team': 'Nottingham Forest', 'away_team': 'Crystal Palace', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Crystal Palace', 'price': 3.2}, {'name': 'Nottingham Forest', 'price': 2.25}, {'name': 'Draw', 'price': 3.45}]}]}]}, {'id': 'efb7bcd1f4959bf80197ec581b077cb2', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T15:00:00Z', 'home_team': 'Sheffield United', 'away_team': 'Fulham', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Fulham', 'price': 1.71}, {'name': 'Sheffield United', 'price': 4.4}, {'name': 'Draw', 'price': 4.2}]}]}]}, {'id': '8a065e80284e1157870534a772c62305', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T15:00:00Z', 'home_team': 'Tottenham Hotspur', 'away_team': 'Luton', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Luton', 'price': 10.0}, {'name': 'Tottenham Hotspur', 'price': 1.23}, {'name': 'Draw', 'price': 7.0}]}]}]}, {'id': '60b84c40ac236905064dae0535ba9c73', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T17:30:00Z', 'home_team': 'Aston Villa', 'away_team': 'Wolverhampton Wanderers', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Aston Villa', 'price': 1.65}, {'name': 'Wolverhampton Wanderers', 'price': 4.8}, {'name': 'Draw', 'price': 4.3}]}]}]}, {'id': '3c3df999f07010248fb7e25e24bc851e', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-30T20:00:00Z', 'home_team': 'Brentford', 'away_team': 'Manchester United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Brentford', 'price': 2.95}, {'name': 'Manchester United', 'price': 2.2}, {'name': 'Draw', 'price': 3.85}]}]}]}, {'id': '6cc43229e6d4cecb17a81350fadc348e', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-31T13:00:00Z', 'home_team': 'Liverpool', 'away_team': 'Brighton and Hove Albion', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 6.75}, {'name': 'Liverpool', 'price': 1.38}, {'name': 'Draw', 'price': 5.6}]}]}]}, {'id': '742a2b03e7bda7de65179b2a3eee8bd2', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-03-31T15:30:00Z', 'home_team': 'Manchester City', 'away_team': 'Arsenal', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Arsenal', 'price': 3.75}, {'name': 'Manchester City', 'price': 1.91}, {'name': 'Draw', 'price': 3.75}]}]}]}, {'id': '2b45606a19467a04cbe30aabdba5f6d9', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-02T18:30:00Z', 'home_team': 'Newcastle United', 'away_team': 'Everton', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Everton', 'price': 4.0}, {'name': 'Newcastle United', 'price': 1.8}, {'name': 'Draw', 'price': 4.0}]}]}]}, {'id': '5d50cb1b7d2e3290d56d0398e01e60e3', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-02T18:30:00Z', 'home_team': 'Nottingham Forest', 'away_team': 'Fulham', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Fulham', 'price': 2.6}, {'name': 'Nottingham Forest', 'price': 2.65}, {'name': 'Draw', 'price': 3.45}]}]}]}, {'id': '69763436c65e956ddc950c436b64a290', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-02T18:45:00Z', 'home_team': 'Bournemouth', 'away_team': 'Crystal Palace', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Bournemouth', 'price': 1.87}, {'name': 'Crystal Palace', 'price': 3.9}, {'name': 'Draw', 'price': 3.85}]}]}]}, {'id': '2883b9e70f9f90877c85ebb1bceebf82', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-02T18:45:00Z', 'home_team': 'Burnley', 'away_team': 'Wolverhampton Wanderers', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Burnley', 'price': 2.85}, {'name': 'Wolverhampton Wanderers', 'price': 2.35}, {'name': 'Draw', 'price': 3.6}]}]}]}, {'id': '10d617cd5230f91dd2886bc5249d2f63', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-02T19:15:00Z', 'home_team': 'West Ham United', 'away_team': 'Tottenham Hotspur', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Tottenham Hotspur', 'price': 2.1}, {'name': 'West Ham United', 'price': 3.05}, {'name': 'Draw', 'price': 4.0}]}]}]}, {'id': '7801e89270a952704db9fe98f66720b9', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-03T18:30:00Z', 'home_team': 'Arsenal', 'away_team': 'Luton', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Arsenal', 'price': 1.15}, {'name': 'Luton', 'price': 15.0}, {'name': 'Draw', 'price': 8.75}]}]}]}, {'id': 'ed20905dccc1b8fd3c7e553e8c2e7dbe', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-03T18:30:00Z', 'home_team': 'Brentford', 'away_team': 'Brighton and Hove Albion', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Brentford', 'price': 2.6}, {'name': 'Brighton and Hove Albion', 'price': 2.45}, {'name': 'Draw', 'price': 3.8}]}]}]}, {'id': '4c51af29ed929e650f9be88ab4ae5d77', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-03T19:15:00Z', 'home_team': 'Manchester City', 'away_team': 'Aston Villa', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Aston Villa', 'price': 9.25}, {'name': 'Manchester City', 'price': 1.27}, {'name': 'Draw', 'price': 6.25}]}]}]}, {'id': 'bb4fa8be4734f8faaa37de47c0423b29', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-04T18:30:00Z', 'home_team': 'Liverpool', 'away_team': 'Sheffield United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Liverpool', 'price': 1.1}, {'name': 'Sheffield United', 'price': 19.0}, {'name': 'Draw', 'price': 11.0}]}]}]}, {'id': '669758585d86adfedda3eed1dbedb47a', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-04T19:15:00Z', 'home_team': 'Chelsea', 'away_team': 'Manchester United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Chelsea', 'price': 2.0}, {'name': 'Manchester United', 'price': 3.4}, {'name': 'Draw', 'price': 3.95}]}]}]}, {'id': 'aa25689e103b645febb56301485aa739', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T11:30:00Z', 'home_team': 'Crystal Palace', 'away_team': 'Manchester City', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Crystal Palace', 'price': 9.0}, {'name': 'Manchester City', 'price': 1.31}, {'name': 'Draw', 'price': 5.6}]}]}]}, {'id': 'f089aa5e8ff6db585da034202166e655', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T14:00:00Z', 'home_team': 'Aston Villa', 'away_team': 'Brentford', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Aston Villa', 'price': 1.71}, {'name': 'Brentford', 'price': 5.0}, {'name': 'Draw', 'price': 3.7}]}]}]}, {'id': 'b228cf71ae51253f85681f7d532ae777', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T14:00:00Z', 'home_team': 'Luton', 'away_team': 'Bournemouth', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Bournemouth', 'price': 2.1}, {'name': 'Luton', 'price': 3.4}, {'name': 'Draw', 'price': 3.55}]}]}]}, {'id': 'abd63bd4c706e3c9a8bc92ad7aa903ea', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T14:00:00Z', 'home_team': 'Everton', 'away_team': 'Burnley', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Burnley', 'price': 5.0}, {'name': 'Everton', 'price': 1.74}, {'name': 'Draw', 'price': 3.65}]}]}]}, {'id': '3881f0fcbcfd89e89c78a015ecdf947b', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T14:00:00Z', 'home_team': 'Fulham', 'away_team': 'Newcastle United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Fulham', 'price': 2.75}, {'name': 'Newcastle United', 'price': 2.5}, {'name': 'Draw', 'price': 3.45}]}]}]}, {'id': '1f772e8d8642f23015d7f5f320e5010f', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T14:00:00Z', 'home_team': 'Wolverhampton Wanderers', 'away_team': 'West Ham United', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'West Ham United', 'price': 2.75}, {'name': 'Wolverhampton Wanderers', 'price': 2.5}, {'name': 'Draw', 'price': 3.45}]}]}]}, {'id': '5b908d12a76265b0d54e24e7e0a0e185', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-06T16:30:00Z', 'home_team': 'Brighton and Hove Albion', 'away_team': 'Arsenal', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Arsenal', 'price': 1.74}, {'name': 'Brighton and Hove Albion', 'price': 4.5}, {'name': 'Draw', 'price': 3.95}]}]}]}, {'id': '0be20dfb5c98e93071442812ab84d57b', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-07T14:30:00Z', 'home_team': 'Manchester United', 'away_team': 'Liverpool', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Liverpool', 'price': 1.91}, {'name': 'Manchester United', 'price': 4.0}, {'name': 'Draw', 'price': 3.6}]}]}]}, {'id': 'a003a42901e673a63784a2b0c8abfb52', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-07T16:30:00Z', 'home_team': 'Sheffield United', 'away_team': 'Chelsea', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Chelsea', 'price': 1.5}, {'name': 'Sheffield United', 'price': 5.75}, {'name': 'Draw', 'price': 4.7}]}]}]}, {'id': '79ad800813481c45cdb516eb9b17a34b', 'sport_key': 'soccer_epl', 'sport_title': 'EPL', 'commence_time': '2024-04-08T19:00:00Z', 'home_team': 'Tottenham Hotspur', 'away_team': 'Nottingham Forest', 'bookmakers': [{'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-03-27T02:26:05Z', 'markets': [{'key': 'h2h', 'last_update': '2024-03-27T02:26:05Z', 'outcomes': [{'name': 'Nottingham Forest', 'price': 7.0}, {'name': 'Tottenham Hotspur', 'price': 1.4}, {'name': 'Draw', 'price': 5.2}]}]}]}]

In [15]:
# Initialize an empty list to hold the simplified odds data
simplified_odds_list = []

# Iterate over the odds data
for event in odds_data:
    # Extract the essential information
    event_name = event.get('sport_title', 'No sport title')
    home_team = event.get('home_team', 'No home team')
    away_team = event.get('away_team', 'No away team')
    start_time = event.get('commence_time', 'No start time')
    
    # Initialize default odds
    home_team_odds = 'N/A'
    away_team_odds = 'N/A'
    draw_odds = 'N/A'  # Initialize draw odds

    # If there are bookmakers data available
    if event.get('bookmakers'):
        # Look for the Bovada bookmaker in the list
        for bookmaker in event['bookmakers']:
            if bookmaker['key'].lower() == 'bovada':  # Ensure case-insensitive matching
                # Assuming 'markets' is a list and we're interested in the first item (h2h)
                markets = bookmaker.get('markets', [])
                if markets:
                    # Assuming the structure of 'outcomes' in the first market
                    outcomes = markets[0].get('outcomes', [])
                    for outcome in outcomes:
                        # Assign odds based on the team or if it's a draw
                        if outcome['name'] == home_team:
                            home_team_odds = outcome.get('price', 'N/A')
                        elif outcome['name'] == away_team:
                            away_team_odds = outcome.get('price', 'N/A')
                        elif outcome['name'].lower() == 'draw':  # Checking for a draw
                            draw_odds = outcome.get('price', 'N/A')
                
                # Once we've found Bovada and extracted the odds, no need to check other bookmakers
                break

    # Create a simplified representation of the event including draw odds
    simplified_event = f"{event_name}: {home_team} vs. {away_team}, Date: {start_time}, Home Odds: {home_team_odds}, Away Odds: {away_team_odds}, Draw Odds: {draw_odds}"
    
    # Add to the list
    simplified_odds_list.append(simplified_event)

# Now, 'simplified_odds_list' contains a more readable version of the odds data, including draw odds
for item in simplified_odds_list:
    print(item)

EPL: Newcastle United vs. West Ham United, Date: 2024-03-30T12:30:00Z, Home Odds: 1.83, Away Odds: 3.8, Draw Odds: 4.1
EPL: Bournemouth vs. Everton, Date: 2024-03-30T15:00:00Z, Home Odds: 2.15, Away Odds: 3.25, Draw Odds: 3.6
EPL: Chelsea vs. Burnley, Date: 2024-03-30T15:00:00Z, Home Odds: 1.31, Away Odds: 8.5, Draw Odds: 6.0
EPL: Nottingham Forest vs. Crystal Palace, Date: 2024-03-30T15:00:00Z, Home Odds: 2.25, Away Odds: 3.2, Draw Odds: 3.45
EPL: Sheffield United vs. Fulham, Date: 2024-03-30T15:00:00Z, Home Odds: 4.4, Away Odds: 1.71, Draw Odds: 4.2
EPL: Tottenham Hotspur vs. Luton, Date: 2024-03-30T15:00:00Z, Home Odds: 1.23, Away Odds: 10.0, Draw Odds: 7.0
EPL: Aston Villa vs. Wolverhampton Wanderers, Date: 2024-03-30T17:30:00Z, Home Odds: 1.65, Away Odds: 4.8, Draw Odds: 4.3
EPL: Brentford vs. Manchester United, Date: 2024-03-30T20:00:00Z, Home Odds: 2.95, Away Odds: 2.2, Draw Odds: 3.85
EPL: Liverpool vs. Brighton and Hove Albion, Date: 2024-03-31T13:00:00Z, Home Odds: 1.38, Away Odds: 6.75, Draw Odds: 5.6
EPL: Manchester City vs. Arsenal, Date: 2024-03-31T15:30:00Z, Home Odds: 1.91, Away Odds: 3.75, Draw Odds: 3.75
EPL: Newcastle United vs. Everton, Date: 2024-04-02T18:30:00Z, Home Odds: 1.8, Away Odds: 4.0, Draw Odds: 4.0
EPL: Nottingham Forest vs. Fulham, Date: 2024-04-02T18:30:00Z, Home Odds: 2.65, Away Odds: 2.6, Draw Odds: 3.45
EPL: Bournemouth vs. Crystal Palace, Date: 2024-04-02T18:45:00Z, Home Odds: 1.87, Away Odds: 3.9, Draw Odds: 3.85
EPL: Burnley vs. Wolverhampton Wanderers, Date: 2024-04-02T18:45:00Z, Home Odds: 2.85, Away Odds: 2.35, Draw Odds: 3.6
EPL: West Ham United vs. Tottenham Hotspur, Date: 2024-04-02T19:15:00Z, Home Odds: 3.05, Away Odds: 2.1, Draw Odds: 4.0
EPL: Arsenal vs. Luton, Date: 2024-04-03T18:30:00Z, Home Odds: 1.15, Away Odds: 15.0, Draw Odds: 8.75
EPL: Brentford vs. Brighton and Hove Albion, Date: 2024-04-03T18:30:00Z, Home Odds: 2.6, Away Odds: 2.45, Draw Odds: 3.8
EPL: Manchester City vs. Aston Villa, Date: 2024-04-03T19:15:00Z, Home Odds: 1.27, Away Odds: 9.25, Draw Odds: 6.25
EPL: Liverpool vs. Sheffield United, Date: 2024-04-04T18:30:00Z, Home Odds: 1.1, Away Odds: 19.0, Draw Odds: 11.0
EPL: Chelsea vs. Manchester United, Date: 2024-04-04T19:15:00Z, Home Odds: 2.0, Away Odds: 3.4, Draw Odds: 3.95
EPL: Crystal Palace vs. Manchester City, Date: 2024-04-06T11:30:00Z, Home Odds: 9.0, Away Odds: 1.31, Draw Odds: 5.6
EPL: Aston Villa vs. Brentford, Date: 2024-04-06T14:00:00Z, Home Odds: 1.71, Away Odds: 5.0, Draw Odds: 3.7
EPL: Luton vs. Bournemouth, Date: 2024-04-06T14:00:00Z, Home Odds: 3.4, Away Odds: 2.1, Draw Odds: 3.55
EPL: Everton vs. Burnley, Date: 2024-04-06T14:00:00Z, Home Odds: 1.74, Away Odds: 5.0, Draw Odds: 3.65
EPL: Fulham vs. Newcastle United, Date: 2024-04-06T14:00:00Z, Home Odds: 2.75, Away Odds: 2.5, Draw Odds: 3.45
EPL: Wolverhampton Wanderers vs. West Ham United, Date: 2024-04-06T14:00:00Z, Home Odds: 2.5, Away Odds: 2.75, Draw Odds: 3.45
EPL: Brighton and Hove Albion vs. Arsenal, Date: 2024-04-06T16:30:00Z, Home Odds: 4.5, Away Odds: 1.74, Draw Odds: 3.95
EPL: Manchester United vs. Liverpool, Date: 2024-04-07T14:30:00Z, Home Odds: 4.0, Away Odds: 1.91, Draw Odds: 3.6
EPL: Sheffield United vs. Chelsea, Date: 2024-04-07T16:30:00Z, Home Odds: 5.75, Away Odds: 1.5, Draw Odds: 4.7
EPL: Tottenham Hotspur vs. Nottingham Forest, Date: 2024-04-08T19:00:00Z, Home Odds: 1.4, Away Odds: 7.0, Draw Odds: 5.2

In [16]:
odds_data_list = []

for event in odds_data:
    home_team = event.get('home_team')
    away_team = event.get('away_team')
    start_time = event.get('commence_time')  # Assuming datetime format or additional parsing might be needed
    
    # Initialize odds
    home_odds = 'N/A'
    away_odds = 'N/A'
    draw_odds = 'N/A'  # Initialize draw odds variable

    # Iterate through bookmakers to find Bovada and extract the odds
    for bookmaker in event.get('bookmakers', []):
        if bookmaker['key'].lower() == 'bovada':  # Ensure case-insensitive matching
            markets = bookmaker.get('markets', [])
            if markets:
                outcomes = markets[0].get('outcomes', [])
                for outcome in outcomes:
                    # Check and assign odds based on the team or if it's a draw
                    if outcome['name'] == home_team:
                        home_odds = outcome.get('price', 'N/A')
                    elif outcome['name'] == away_team:
                        away_odds = outcome.get('price', 'N/A')
                    elif outcome['name'].lower() == 'draw':  # Check for draw odds
                        draw_odds = outcome.get('price', 'N/A')

    # Append the data including draw odds to the list
    odds_data_list.append({
        'Game Matchup': f"{home_team} vs. {away_team}",
        'Home Odds': home_odds,
        'Away Odds': away_odds,
        'Draw Odds': draw_odds,  # Include draw odds
        'Start Time': start_time
    })

# Convert the list to a DataFrame
odds_df = pd.DataFrame(odds_data_list)

In [17]:
name_replacements = {
    'Brighton and Hove Albion': 'Brighton',
    'West Ham United': 'West Ham',
    'Tottenham Hotspur': 'Tottenham'
    # Add any other specific replacements you need here
}
import pandas as pd

# Assuming odds_df is already defined

# Apply replacements in the 'Game Matchup' column
for original_name, new_name in name_replacements.items():
    odds_df['Game Matchup'] = odds_df['Game Matchup'].str.replace(original_name, new_name, regex=False)

# Display the updated DataFrame
print(odds_df)

                               Game Matchup  Home Odds  Away Odds  Draw Odds  \
0             Newcastle United vs. West Ham       1.83       3.80       4.10
1                   Bournemouth vs. Everton       2.15       3.25       3.60
2                       Chelsea vs. Burnley       1.31       8.50       6.00
3      Nottingham Forest vs. Crystal Palace       2.25       3.20       3.45
4               Sheffield United vs. Fulham       4.40       1.71       4.20
5                       Tottenham vs. Luton       1.23      10.00       7.00
6   Aston Villa vs. Wolverhampton Wanderers       1.65       4.80       4.30
7           Brentford vs. Manchester United       2.95       2.20       3.85
8                    Liverpool vs. Brighton       1.38       6.75       5.60
9               Manchester City vs. Arsenal       1.91       3.75       3.75
10             Newcastle United vs. Everton       1.80       4.00       4.00
11             Nottingham Forest vs. Fulham       2.65       2.60       3.45
12           Bournemouth vs. Crystal Palace       1.87       3.90       3.85
13      Burnley vs. Wolverhampton Wanderers       2.85       2.35       3.60
14                   West Ham vs. Tottenham       3.05       2.10       4.00
15                        Arsenal vs. Luton       1.15      15.00       8.75
16                   Brentford vs. Brighton       2.60       2.45       3.80
17          Manchester City vs. Aston Villa       1.27       9.25       6.25
18           Liverpool vs. Sheffield United       1.10      19.00      11.00
19            Chelsea vs. Manchester United       2.00       3.40       3.95
20       Crystal Palace vs. Manchester City       9.00       1.31       5.60
21                Aston Villa vs. Brentford       1.71       5.00       3.70
22                    Luton vs. Bournemouth       3.40       2.10       3.55
23                      Everton vs. Burnley       1.74       5.00       3.65
24              Fulham vs. Newcastle United       2.75       2.50       3.45
25     Wolverhampton Wanderers vs. West Ham       2.50       2.75       3.45
26                     Brighton vs. Arsenal       4.50       1.74       3.95
27          Manchester United vs. Liverpool       4.00       1.91       3.60
28             Sheffield United vs. Chelsea       5.75       1.50       4.70
29          Tottenham vs. Nottingham Forest       1.40       7.00       5.20

              Start Time
0   2024-03-30T12:30:00Z
1   2024-03-30T15:00:00Z
2   2024-03-30T15:00:00Z
3   2024-03-30T15:00:00Z
4   2024-03-30T15:00:00Z
5   2024-03-30T15:00:00Z
6   2024-03-30T17:30:00Z
7   2024-03-30T20:00:00Z
8   2024-03-31T13:00:00Z
9   2024-03-31T15:30:00Z
10  2024-04-02T18:30:00Z
11  2024-04-02T18:30:00Z
12  2024-04-02T18:45:00Z
13  2024-04-02T18:45:00Z
14  2024-04-02T19:15:00Z
15  2024-04-03T18:30:00Z
16  2024-04-03T18:30:00Z
17  2024-04-03T19:15:00Z
18  2024-04-04T18:30:00Z
19  2024-04-04T19:15:00Z
20  2024-04-06T11:30:00Z
21  2024-04-06T14:00:00Z
22  2024-04-06T14:00:00Z
23  2024-04-06T14:00:00Z
24  2024-04-06T14:00:00Z
25  2024-04-06T14:00:00Z
26  2024-04-06T16:30:00Z
27  2024-04-07T14:30:00Z
28  2024-04-07T16:30:00Z
29  2024-04-08T19:00:00Z

In [18]:
# Assuming 'projected_goals_df' exists and has a 'Game Matchup' column
merged_df = pd.merge(projected_goals_df, odds_df, on='Game Matchup', how='left')

# Now 'merged_df' contains both the projected probabilities and the odds

In [19]:
merged_df

,Game Matchup,Projected Home Goals,Projected Away Goals,Total Projected Goals,Home Win Probability,Away Win Probability,Draw Probability,Home Odds,Away Odds,Draw Odds,Start Time
0,Aston Villa vs. Wolverhampton Wanderers,2.433578,1.376747,3.810325,61.04%,20.52%,18.44%,1.65,4.80,4.30,2024-03-30T17:30:00Z
1,Bournemouth vs. Everton,1.589930,1.504632,3.094562,39.74%,36.76%,23.50%,2.15,3.25,3.60,2024-03-30T15:00:00Z
2,Brentford vs. Manchester United,2.001929,1.684820,3.686749,45.58%,32.87%,21.55%,2.95,2.20,3.85,2024-03-30T20:00:00Z
3,Chelsea vs. Burnley,2.566466,0.723312,3.289778,77.19%,8.31%,14.50%,1.31,8.50,6.00,2024-03-30T15:00:00Z
4,Newcastle United vs. West Ham,3.040199,1.381083,4.421282,69.85%,14.92%,15.23%,1.83,3.80,4.10,2024-03-30T12:30:00Z
5,Nottingham Forest vs. Crystal Palace,1.383419,0.834289,2.217707,49.85%,23.06%,27.09%,2.25,3.20,3.45,2024-03-30T15:00:00Z
6,Sheffield United vs. Fulham,1.338408,1.769463,3.107872,29.31%,48.81%,21.88%,4.40,1.71,4.20,2024-03-30T15:00:00Z
7,Tottenham vs. Luton,3.600562,1.419110,5.019672,77.30%,10.76%,11.94%,1.23,10.00,7.00,2024-03-30T15:00:00Z
8,Liverpool vs. Brighton,2.691901,1.022305,3.714206,72.17%,12.57%,15.26%,1.38,6.75,5.60,2024-03-31T13:00:00Z
9,Manchester City vs. Arsenal,0.891054,1.091272,1.982326,29.31%,39.55%,31.14%,1.91,3.75,3.75,2024-03-31T15:30:00Z

In [20]:
# Convert percentage strings to decimal probabilities
merged_df['Home Win Probability'] = merged_df['Home Win Probability'].str.rstrip('%').astype(float) / 100
merged_df['Away Win Probability'] = merged_df['Away Win Probability'].str.rstrip('%').astype(float) / 100
merged_df['Draw Probability'] = merged_df['Draw Probability'].str.rstrip('%').astype(float) / 100
# Calculate implied odds
merged_df['Implied Home Odds'] = 1 / merged_df['Home Win Probability']
merged_df['Implied Away Odds'] = 1 / merged_df['Away Win Probability']
merged_df['Implied Draw Odds'] = 1 / merged_df['Draw Probability']
# Create a new DataFrame with implied odds
implied_odds_df = merged_df[['Game Matchup', 'Implied Home Odds', 'Implied Away Odds', 'Implied Draw Odds', 'Home Odds', 'Away Odds', 'Draw Odds']].copy()

In [21]:
# Calculate edge for home win
implied_odds_df['Home Win Edge'] = round((1 / implied_odds_df['Implied Home Odds']) * implied_odds_df['Home Odds'] - 1, 2)

# Calculate edge for away win
implied_odds_df['Away Win Edge'] = round((1 / implied_odds_df['Implied Away Odds']) * implied_odds_df['Away Odds'] - 1, 2)

# Calculate edge for draw
implied_odds_df['Draw Edge'] = round((1 / implied_odds_df['Implied Draw Odds']) * implied_odds_df['Draw Odds'] - 1, 2)

# Round implied odds to 2 decimal points
implied_odds_df['Implied Home Odds'] = round(implied_odds_df['Implied Home Odds'], 2)
implied_odds_df['Implied Away Odds'] = round(implied_odds_df['Implied Away Odds'], 2)
implied_odds_df['Implied Draw Odds'] = round(implied_odds_df['Implied Draw Odds'], 2)

implied_odds_df

,Game Matchup,Implied Home Odds,Implied Away Odds,Implied Draw Odds,Home Odds,Away Odds,Draw Odds,Home Win Edge,Away Win Edge,Draw Edge
0,Aston Villa vs. Wolverhampton Wanderers,1.64,4.87,5.42,1.65,4.80,4.30,0.01,-0.02,-0.21
1,Bournemouth vs. Everton,2.52,2.72,4.26,2.15,3.25,3.60,-0.15,0.19,-0.15
2,Brentford vs. Manchester United,2.19,3.04,4.64,2.95,2.20,3.85,0.34,-0.28,-0.17
3,Chelsea vs. Burnley,1.30,12.03,6.90,1.31,8.50,6.00,0.01,-0.29,-0.13
4,Newcastle United vs. West Ham,1.43,6.70,6.57,1.83,3.80,4.10,0.28,-0.43,-0.38
5,Nottingham Forest vs. Crystal Palace,2.01,4.34,3.69,2.25,3.20,3.45,0.12,-0.26,-0.07
6,Sheffield United vs. Fulham,3.41,2.05,4.57,4.40,1.71,4.20,0.29,-0.17,-0.08
7,Tottenham vs. Luton,1.29,9.29,8.38,1.23,10.00,7.00,-0.05,0.08,-0.16
8,Liverpool vs. Brighton,1.39,7.96,6.55,1.38,6.75,5.60,-0.00,-0.15,-0.15
9,Manchester City vs. Arsenal,3.41,2.53,3.21,1.91,3.75,3.75,-0.44,0.48,0.17

In [22]:
# Assuming 'projected_goals_df' is the DataFrame containing projected goals

# Merge the implied odds DataFrame with the projected goals DataFrame on the 'Game Matchup' column
implied_odds_with_goals = implied_odds_df.merge(projected_goals_df, on='Game Matchup', how='left')

# Display the DataFrame with projected goals added
implied_odds_with_goals

,Game Matchup,Implied Home Odds,Implied Away Odds,Implied Draw Odds,Home Odds,Away Odds,Draw Odds,Home Win Edge,Away Win Edge,Draw Edge,Projected Home Goals,Projected Away Goals,Total Projected Goals,Home Win Probability,Away Win Probability,Draw Probability
0,Aston Villa vs. Wolverhampton Wanderers,1.64,4.87,5.42,1.65,4.80,4.30,0.01,-0.02,-0.21,2.433578,1.376747,3.810325,61.04%,20.52%,18.44%
1,Bournemouth vs. Everton,2.52,2.72,4.26,2.15,3.25,3.60,-0.15,0.19,-0.15,1.589930,1.504632,3.094562,39.74%,36.76%,23.50%
2,Brentford vs. Manchester United,2.19,3.04,4.64,2.95,2.20,3.85,0.34,-0.28,-0.17,2.001929,1.684820,3.686749,45.58%,32.87%,21.55%
3,Chelsea vs. Burnley,1.30,12.03,6.90,1.31,8.50,6.00,0.01,-0.29,-0.13,2.566466,0.723312,3.289778,77.19%,8.31%,14.50%
4,Newcastle United vs. West Ham,1.43,6.70,6.57,1.83,3.80,4.10,0.28,-0.43,-0.38,3.040199,1.381083,4.421282,69.85%,14.92%,15.23%
5,Nottingham Forest vs. Crystal Palace,2.01,4.34,3.69,2.25,3.20,3.45,0.12,-0.26,-0.07,1.383419,0.834289,2.217707,49.85%,23.06%,27.09%
6,Sheffield United vs. Fulham,3.41,2.05,4.57,4.40,1.71,4.20,0.29,-0.17,-0.08,1.338408,1.769463,3.107872,29.31%,48.81%,21.88%
7,Tottenham vs. Luton,1.29,9.29,8.38,1.23,10.00,7.00,-0.05,0.08,-0.16,3.600562,1.419110,5.019672,77.30%,10.76%,11.94%
8,Liverpool vs. Brighton,1.39,7.96,6.55,1.38,6.75,5.60,-0.00,-0.15,-0.15,2.691901,1.022305,3.714206,72.17%,12.57%,15.26%
9,Manchester City vs. Arsenal,3.41,2.53,3.21,1.91,3.75,3.75,-0.44,0.48,0.17,0.891054,1.091272,1.982326,29.31%,39.55%,31.14%

In [23]:
# Save the DataFrame to a CSV file
implied_odds_with_goals.to_csv('epl_odds_3-29.csv', index=False)

In [24]:
# Define a function to color code values based on conditions
def color_edges(val):
    if val < 0:
        return 'background-color: maroon'
    elif 0.0 <= val < 0.1:
        return 'background-color: yellow'
    else:
        return 'background-color: green'

# Apply the styling to the specified columns
styled_df = implied_odds_with_goals.style.applymap(color_edges, subset=['Home Win Edge', 'Away Win Edge', 'Draw Edge'])

# Display the styled DataFrame
styled_df

C:\Users\jbuck\AppData\Local\Temp\ipykernel_4480\2992074314.py:11: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  styled_df = implied_odds_with_goals.style.applymap(color_edges, subset=['Home Win Edge', 'Away Win Edge', 'Draw Edge'])

In [24]:
# Round all numbers to the 2nd decimal place
styled_df = styled_df.format('{:.2f}')

# Display the styled DataFrame with rounded numbers
styled_df

ValueError: Unknown format code 'f' for object of type 'str'